name: transcript_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  audioplayers: ^6.3.0
  path_provider: ^2.1.5
  # todo-01-init-01: install dependencies
  google_generative_ai: ^0.4.6
  build_runner: ^2.4.15
  mime: ^2.0.0
  envied: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # todo-01-init-01: install dependencies
  # todo-01-init-02: setup environment variable
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
