name: house_price_predictor_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  # todo-02-init-01: install dependencies
  intl: ^0.20.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # todo-01-init-01: download model, put the assets folder, and register it to pubspec.yaml
  assets:
    - assets/
