name: tflite_vision_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  camera: 0.10.6
  image: ^4.5.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# todo-01-init-01: download the model and put it on assets folder (ssd_mobilenet and labelmap)
# todo-01-init-02: change all name from ImageClassification into ObjectDetection
# image_classification_provider.dart, image_classification_service.dart, Title App, 