name: house_price_predictor_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.2
  tflite_flutter: ^0.11.0
  # todo-01: install dependencies
  firebase_core: ^3.12.0
  firebase_ml_model_downloader: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # todo-07: remove folder assets and detele the dependency
