name: chatbot_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.6+2
  # todo-01-setup-01: install dependencies and dev_dependencies
  google_generative_ai: ^0.4.6
  build_runner: ^2.4.15
  mime: ^2.0.0
  envied: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # todo-01-setup-02: setup env variable and exclude it from .gitignore
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
